version: 2

machine:
  services:
    - docker
  timezone: Europe/Paris

jobs:
  build:
    working_directory: /go/src/cachet/cli
    docker:
      - image: circleci/golang:1.8
        environment:
          GOPATH: /go
    steps:
      - checkout:
          path: /go/src/cachet
      - run:
          name: Checking GO version...
          command: go version
      - run:
          name: Downloading dependencies...
          command: go get .
      - run:
          name: Building...
          command: go build -ldflags "-X main.AppBranch=`git describe --tags --abbrev=0` -X main.Build=${CIRCLE_SHA1} -X main.BuildDate=`date +%Y-%m-%d_%H:%M:%S`" -o cachet_monitor
      - run:
          name: Checking delivery...
          command: ls -l cachet_monitor
      - run:
          name: Saving git tag...
          command: git describe --tags --abbrev=0 > /go/src/cachet/cli/cachet-monitory.tag
      - run:
          name: Getting default configuration files...
          command: cp /go/src/cachet/example.config.* /go/src/cachet/cli
      - save_cache:
          key: cachet-monitory-delivery-cache-{{ checksum "cachet_monitor" }}
          paths:
            - /go/src/cachet/cli

  test:
    working_directory: /go/src/cachet/cli
    docker:
      - image: circleci/golang:1.8
    steps:
      - restore-cache:
          keys:
            - cachet-monitory-delivery-cache-
      - run:
          name: Listing build version...
          command: ./cachet_monitor --version
      - run:
          name: Testing YML configuration...
          command: ./cachet_monitor -c example.config.yml --config-test
      - run:
          name: Testing JSON configuration...
          command: ./cachet_monitor -c example.config.json --config-test
      - store_artifacts:
          path: /go/src/cachet/cli/cachet_monitor
          destination: artifact-file

  release:
    working_directory: /go/src/cachet/cli
    docker:
      - image: circleci/golang:1.8
    steps:
      - restore-cache:
          keys:
            - cachet-monitory-delivery-cache-
      - run:
          name: Downloading GitHub Release...
          command: wget -O./ghr.zip https://github.com/tcnksm/ghr/releases/download/v0.5.4/ghr_v0.5.4_linux_amd64.zip && unzip ghr.zip && chmod +x ./ghr
      - run:
          name: Preparing release...
          command: mkdir ./dist && mv ./cachet_monitor ./dist && cat cachet-monitory.tag
      - run:
          name: GitHub Release...
          command: |
            LATEST_TAG=`cat cachet-monitory.tag`
            if [[ "`echo ${LATEST_TAG} | tr '[:upper:]' '[:lower:]'`" == *"snapshot"* ]]; then
              echo "Prereleasing '${LATEST_TAG}'" && ./ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} --delete --prerelease --replace ${LATEST_TAG} ./dist
              echo "Prereleasing '${LATEST_TAG}'" && ./ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} --delete --prerelease --replace snapshot ./dist
            else
              echo "Releasing '${LATEST_TAG}'" && ./ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} --delete --replace ${LATEST_TAG} ./dist
            fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - build
            - test
